# Generated by Django 5.1.5 on 2025-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
